# Workflow for macOS (latest).
name: macOS

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    # We want to run on external PRs, but not on our own internal PRs as
    # they'll be run by the push to the branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '3rdparty/eventuals'

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v1

      - name: Check for bazel
        run: bazel --version

      - name: Build
        run: bazel build --spawn_strategy=local --copt="-g" --strip="never" :eventuals

      - name: Debug Build using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: bazel test --spawn_strategy=local --copt="-g" --strip="never" --test_output=errors test:eventuals --test_arg=--gtest_shuffle --test_arg=--gtest_repeat=100 --experimental_ui_max_stdouterr_bytes=-1

      - name: Debug Test using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
